NUM_NODES = 10
NUM_EDGES = 15
DEGREE = 3
NUM_MULTICAST_REQUESTS = 2
MAX_MULTICAST_SIZE = NUM_NODES//5
TOLERANCE = 0.9

COLGEN_ID = "CG"
JZ2008_ID = "JZ"
SOLVER_ID_LIST = [COLGEN_ID, JZ2008_ID]
BLOCK_APPROX_LEVELS = [2, 1]

# DEPRECATED
# NATURAL = 0
# UNIFORM = 1
# PERTURB = 2