NUM_NODES = 10
NUM_EDGES = 15
DEGREE = 3
NUM_MULTICAST_REQUESTS = 2
MAX_MULTICAST_SIZE = NUM_NODES//2
DELAY = 2*MAX_MULTICAST_SIZE
TOLERANCE = 0.3
MAX_ITERS = 500
MAX_TIME = 180

# Stop Flags
STOP_FLAG_TOL_MET = 0b10000
STOP_FLAG_REDCOST = 0b01000
STOP_DUALITYMATCH = 0b00100
STOP_FLAG_MAXITER = 0b00010
STOP_FLAG_TIMEOUT = 0b00001

# Identifiers for various solvers
COLGEN_ID = "CG"
JZ2008_ID = "JZ"
FULLIP_ID = "IP"
SOLVER_ID_LIST = [
    COLGEN_ID, 
    JZ2008_ID, 
    FULLIP_ID
]
BLOCK_APPROX_LEVELS = [
    2,
    1,
#    "Delay"
]

# DEPRECATED
# NATURAL = 0
# UNIFORM = 1
# PERTURB = 2